# Generated by Django 4.2 on 2023-05-09 17:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number starting with 05, 06 or 07 and has 10 digits in total', regex='^0[5-7][0-9]{8}$')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.CharField(max_length=50)),
                ('policy', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(default='default.png', upload_to='profile_pics')),
            ],
            options={
                'db_table': 'auth_client',
            },
        ),
    ]
