# Generated by Django 4.2 on 2023-05-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0003_alter_appointment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tests_requested',
            field=models.ManyToManyField(to='main_home.testoffered'),
        ),
    ]
