# Generated by Django 4.2 on 2023-05-16 18:07

from django.db import migrations, models
import main_home.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0004_alter_appointment_tests_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(validators=[main_home.models.validate_date_not_past]),
        ),
    ]
