# Generated by Django 4.2 on 2023-05-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0006_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocument',
            name='image',
            field=models.ImageField(upload_to='medical_documents'),
        ),
    ]
