# Generated by Django 4.2 on 2023-05-17 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_date_of_birth_client_tests_made'),
        ('main_home', '0010_appointment_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
