# Generated by Django 4.2 on 2023-05-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0011_alter_bloodbank_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='submission_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
