# Generated by Django 4.2 on 2023-05-18 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0012_alter_bloodbank_submission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_fee', models.DecimalField(decimal_places=2, default=200.0, max_digits=6)),
                ('tests_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_home.appointment')),
            ],
        ),
    ]
