# Generated by Django 4.2 on 2023-05-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0013_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='nurse_tests_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tests_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
