# Generated by Django 4.2 on 2023-05-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0015_remove_payment_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payed_appointment_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payed_nurse_tests_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payed_tests_fee',
            field=models.BooleanField(default=False),
        ),
    ]
