# Generated by Django 4.2 on 2023-05-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_nurse_date_of_birth'),
        ('main_home', '0016_payment_payed_appointment_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='performed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.ManyToManyField(to='main_home.appointment')),
                ('nurse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nurse.nurse')),
            ],
        ),
    ]
