# Generated by Django 4.2 on 2023-05-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0017_appointment_performed_lobby'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lobby',
            options={'verbose_name_plural': 'Lobbies'},
        ),
    ]
