# Generated by Django 4.2 on 2023-05-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0018_alter_lobby_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='clients',
            field=models.ManyToManyField(blank=True, to='main_home.appointment'),
        ),
    ]
