# Generated by Django 4.2 on 2023-05-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0019_alter_lobby_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='blood_sample',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='tests',
        ),
        migrations.AddField(
            model_name='analysisrequest',
            name='tests',
            field=models.ManyToManyField(to='main_home.test'),
        ),
    ]
