# Generated by Django 4.2 on 2023-05-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0020_remove_testresult_blood_sample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='value',
            field=models.FloatField(blank=True),
        ),
    ]
