# Generated by Django 4.2 on 2023-05-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0021_alter_component_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
