# Generated by Django 4.2 on 2023-05-20 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0022_alter_component_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_home.appointment'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_home.report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='test_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_home.testresult'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_home.analysisrequest'),
        ),
    ]
