# Generated by Django 4.2 on 2023-05-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0023_alter_analysisrequest_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_option',
        ),
    ]
