# Generated by Django 4.2 on 2023-05-20 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0025_remove_laboratory_monthly_revenue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='tests_made',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='medical_documents'),
        ),
        migrations.CreateModel(
            name='MonthlyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_home.laboratory')),
            ],
            options={
                'db_table': 'monthly_revenue',
            },
        ),
    ]
