# Generated by Django 4.2 on 2023-05-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0026_remove_laboratory_tests_made_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
