# Generated by Django 4.2 on 2023-06-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0030_alter_chatroom_auditor_alter_chatroom_nurse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='payment_option',
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment_fee',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
    ]
