# Generated by Django 4.2 on 2023-06-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0031_remove_appointment_payment_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='appointment_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
