# Generated by Django 4.2 on 2023-06-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0033_alter_payment_appointment_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
