# Generated by Django 4.2 on 2023-06-05 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_date_of_birth_client_tests_made'),
        ('main_home', '0034_alter_report_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='bloodbank',
            name='client',
        ),
        migrations.RemoveField(
            model_name='bloodbank',
            name='submission_date',
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='capacity',
            field=models.IntegerField(choices=[(400, '400'), (300, '300'), (200, '200')], default=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BloodSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(default='mL', max_length=2)),
                ('submission_date', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_samples', to='main_home.bloodbank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
