# Generated by Django 4.2 on 2023-06-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0037_analysisrequest_diabetes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetesprediction',
            name='blood_glucose_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diabetesprediction',
            name='hba1c_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
