# Generated by Django 4.2 on 2023-06-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0040_rename_diabetes_analysisrequest_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='components',
            field=models.ManyToManyField(blank=True, null=True, to='main_home.component'),
        ),
    ]
