# Generated by Django 4.2 on 2023-06-06 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0042_alter_test_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiabetesPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.BooleanField()),
                ('probability', models.FloatField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_home.analysisrequest')),
            ],
        ),
        migrations.CreateModel(
            name='AnemiaPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.BooleanField()),
                ('probability', models.FloatField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_home.analysisrequest')),
            ],
        ),
    ]
