# Generated by Django 4.2 on 2023-06-06 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0043_diabetesprediction_anemiaprediction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiabetesPrediction',
            new_name='Anemia',
        ),
        migrations.RenameModel(
            old_name='AnemiaPrediction',
            new_name='Diabetes',
        ),
        migrations.AlterField(
            model_name='anemia',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_home.testresult'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_home.testresult'),
        ),
    ]
