# Generated by Django 4.2 on 2023-06-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0051_alter_evaluation_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testoffered',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
