# Generated by Django 4.2 on 2023-06-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0052_appointment_urgent_testoffered_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='codename',
            field=models.CharField(default='bbbc', max_length=10),
            preserve_default=False,
        ),
    ]
