# Generated by Django 4.2 on 2023-06-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0053_bloodbank_codename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='capacity',
            field=models.IntegerField(choices=[(500, '500'), (400, '400'), (300, '300'), (200, '200')]),
        ),
    ]
