# Generated by Django 4.2 on 2023-06-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_home', '0056_alter_analysisrequest_tests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrequest',
            name='tests',
            field=models.ManyToManyField(blank=True, to='main_home.test'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tests_requested',
            field=models.ManyToManyField(blank=True, to='main_home.testoffered'),
        ),
    ]
